-- Insert sample products
INSERT INTO products (name, category, manufacturer, price, description, features, image, badge, status, views) VALUES
(
    'Advanced Combine Harvester X1',
    'Harvesting',
    'AgriTech Pro',
    '$250,000',
    'State-of-the-art combine harvester with GPS navigation and yield mapping capabilities.',
    ARRAY['GPS Navigation', 'Yield Mapping', 'Auto-steering', 'Climate Control'],
    '/placeholder.svg?height=400&width=600',
    'Best Seller',
    'active',
    156
),
(
    'Smart Irrigation System Pro',
    'Irrigation',
    'WaterTech Solutions',
    '$15,000',
    'Intelligent irrigation system with soil moisture sensors and weather integration.',
    ARRAY['Soil Sensors', 'Weather Integration', 'Mobile App Control', 'Water Conservation'],
    '/placeholder.svg?height=400&width=600',
    'Eco-Friendly',
    'active',
    89
),
(
    'Precision Seeding Machine',
    'Seeding',
    'SeedMaster Inc',
    '$45,000',
    'High-precision seeding equipment for optimal crop placement and spacing.',
    ARRAY['Variable Rate Seeding', 'GPS Guidance', 'Seed Monitoring', 'Easy Calibration'],
    '/placeholder.svg?height=400&width=600',
    'New Arrival',
    'active',
    234
),
(
    'Livestock Feed Mixer',
    'Feed Processing',
    'FeedTech Industries',
    '$35,000',
    'Automated feed mixing system for consistent and nutritious livestock feed.',
    ARRAY['Automated Mixing', 'Recipe Storage', 'Load Cells', 'Easy Cleaning'],
    '/placeholder.svg?height=400&width=600',
    'Featured',
    'active',
    67
),
(
    'Soil Preparation Tractor',
    'Soil Preparation',
    'TractorMax',
    '$85,000',
    'Heavy-duty tractor designed for soil preparation and field cultivation.',
    ARRAY['High Horsepower', 'Hydraulic System', 'Comfortable Cabin', 'Fuel Efficient'],
    '/placeholder.svg?height=400&width=600',
    'Premium',
    'active',
    0
),
('Premium Olive Oil Processing Line', 'Food Processing', 'Turkish Machinery Co.', '$250,000', 'Complete olive oil extraction and processing system with modern technology', ARRAY['Cold Press Technology', 'Automated Control', 'High Capacity', 'Quality Certification'], '/placeholder.svg?height=400&width=600', 'Best Seller', 'active', 0),
('Industrial Textile Loom', 'Textile Machinery', 'Anatolia Textiles', '$180,000', 'High-speed industrial loom for premium fabric production', ARRAY['High Speed Operation', 'Digital Control', 'Energy Efficient', 'Low Maintenance'], '/placeholder.svg?height=400&width=600', 'Featured', 'active', 0),
('Marble Processing Equipment', 'Stone Processing', 'Turkish Stone Tech', '$320,000', 'Complete marble cutting and polishing system', ARRAY['Precision Cutting', 'Automated Polishing', 'Dust Collection', 'Safety Systems'], '/placeholder.svg?height=400&width=600', 'Premium', 'active', 0),
('Hazelnut Processing Machine', 'Food Processing', 'Black Sea Machinery', '$150,000', 'Specialized equipment for hazelnut processing and packaging', ARRAY['Shell Removal', 'Sorting System', 'Packaging Integration', 'Quality Control'], '/placeholder.svg?height=400&width=600', 'New Arrival', 'active', 0),
('Ceramic Tile Production Line', 'Ceramics', 'Turkish Ceramics Ltd.', '$450,000', 'Complete ceramic tile manufacturing system', ARRAY['High Temperature Firing', 'Automated Glazing', 'Quality Testing', 'Energy Recovery'], '/placeholder.svg?height=400&width=600', 'Featured', 'active', 0);

-- Insert sample blog posts
INSERT INTO blog_posts (title, excerpt, content, author, author_role, category, tags, image, featured, views, likes, comments, status) VALUES
(
    'The Future of Sustainable Agriculture',
    'Exploring innovative farming techniques that protect our environment while maximizing yield.',
    '<p>Sustainable agriculture is becoming increasingly important as we face climate change challenges. Modern farming techniques are evolving to balance productivity with environmental responsibility.</p><p>Key innovations include precision farming, organic practices, and smart irrigation systems that reduce water waste while maintaining crop quality.</p>',
    'Dr. Sarah Johnson',
    'Agricultural Scientist',
    'Sustainability',
    ARRAY['sustainability', 'innovation', 'environment', 'farming'],
    '/placeholder.svg?height=400&width=600',
    true,
    1245,
    89,
    23,
    'published'
),
(
    'Global Export Trends in Agricultural Equipment',
    'Analysis of international trade patterns and emerging markets for farm machinery.',
    '<p>The global agricultural equipment market is experiencing significant growth, driven by increasing demand for food production and technological advancement.</p><p>Key markets include Asia-Pacific, Latin America, and Africa, where mechanization is rapidly expanding to meet growing food security needs.</p>',
    'Michael Chen',
    'Market Analyst',
    'Export',
    ARRAY['export', 'global trade', 'market analysis', 'equipment'],
    '/placeholder.svg?height=400&width=600',
    true,
    892,
    67,
    15,
    'published'
),
(
    'Smart Technology Integration in Modern Farming',
    'How IoT, AI, and automation are revolutionizing agricultural practices.',
    '<p>The integration of smart technologies in agriculture is transforming how farmers manage their operations. From IoT sensors monitoring soil conditions to AI-powered crop analysis, technology is making farming more efficient and sustainable.</p><p>These innovations help farmers make data-driven decisions, optimize resource usage, and increase productivity while reducing environmental impact.</p>',
    'Emma Rodriguez',
    'Technology Specialist',
    'Technology',
    ARRAY['technology', 'IoT', 'AI', 'automation', 'smart farming'],
    '/placeholder.svg?height=400&width=600',
    false,
    567,
    45,
    8,
    'published'
),
(
    'The Future of Smart Farming Technology',
    'Exploring how AI and IoT are revolutionizing modern agriculture practices.',
    'Smart farming technology is transforming the agricultural landscape. With the integration of AI, IoT sensors, and precision agriculture tools, farmers can now optimize their operations like never before. This comprehensive guide explores the latest innovations in agricultural technology and their impact on crop yields, resource efficiency, and sustainable farming practices.',
    'Dr. Sarah Johnson',
    'Agricultural Technology Expert',
    'Technology',
    ARRAY['Smart Farming', 'AI', 'IoT', 'Precision Agriculture'],
    '/placeholder.svg?height=400&width=600',
    true,
    0,
    0,
    0,
    'published'
),
(
    'Sustainable Export Strategies for Agricultural Products',
    'Best practices for exporting agricultural products while maintaining sustainability.',
    'As global demand for agricultural products continues to grow, sustainable export strategies have become crucial for long-term success. This article discusses eco-friendly packaging, carbon-neutral shipping methods, and sustainable farming practices that appeal to international markets. Learn how to build a sustainable export business that benefits both your bottom line and the environment.',
    'Michael Chen',
    'Export Specialist',
    'Export',
    ARRAY['Sustainability', 'Export', 'Green Practices', 'International Trade'],
    '/placeholder.svg?height=400&width=600',
    false,
    0,
    0,
    0,
    'published'
),
(
    'Innovation in Agricultural Equipment Design',
    'How modern design principles are improving agricultural machinery efficiency.',
    'The agricultural equipment industry is experiencing a design revolution. From ergonomic operator interfaces to energy-efficient systems, modern agricultural machinery is being designed with both functionality and sustainability in mind. This article explores the latest innovations in equipment design and their impact on farming operations.',
    'Emma Rodriguez',
    'Equipment Design Engineer',
    'Innovation',
    ARRAY['Equipment Design', 'Innovation', 'Efficiency', 'Ergonomics'],
    '/placeholder.svg?height=400&width=600',
    true,
    0,
    0,
    0,
    'published'
),
(
    'Market Analysis: Global Agricultural Equipment Trends',
    'Comprehensive analysis of current trends in the global agricultural equipment market.',
    'The global agricultural equipment market is evolving rapidly, driven by technological advancements and changing farming practices. This comprehensive market analysis examines current trends, emerging technologies, and future opportunities in the agricultural equipment sector. Discover key insights that can help guide your business decisions and investment strategies.',
    'Robert Kim',
    'Market Analyst',
    'Market Analysis',
    ARRAY['Market Trends', 'Global Market', 'Investment', 'Business Strategy'],
    '/placeholder.svg?height=400&width=600',
    false,
    0,
    0,
    0,
    'published'
),
('Turkish Export Success in 2024', 'Turkey continues to lead in global exports with record-breaking numbers', 'Turkey has achieved remarkable success in international trade this year, with exports reaching new heights across multiple sectors. The country''s strategic location, quality manufacturing, and competitive pricing have made it a preferred partner for businesses worldwide.', 'Mehmet Özkan', 'Export Director', 'Market Analysis', ARRAY['exports', 'turkey', 'trade', 'success'], '/placeholder.svg?height=400&width=600', true, 0, 0, 0, 'published'),
('Quality Standards in Turkish Manufacturing', 'How Turkish manufacturers maintain world-class quality standards', 'Turkish manufacturing has evolved significantly over the past decade, with companies investing heavily in quality control systems, certifications, and modern technology. This commitment to quality has positioned Turkey as a reliable supplier in global markets.', 'Ayşe Demir', 'Quality Manager', 'Quality Control', ARRAY['quality', 'manufacturing', 'standards', 'certification'], '/placeholder.svg?height=400&width=600', true, 0, 0, 0, 'published'),
('Logistics Excellence in Turkish Exports', 'The backbone of successful international trade', 'Efficient logistics and supply chain management are crucial for successful exports. Turkish companies have developed sophisticated logistics networks that ensure timely delivery and cost-effective transportation to global markets.', 'Can Yılmaz', 'Logistics Specialist', 'Logistics', ARRAY['logistics', 'supply-chain', 'transportation', 'efficiency'], '/placeholder.svg?height=400&width=600', false, 0, 0, 0, 'published'),
('Sustainable Manufacturing Practices', 'Environmental responsibility in Turkish industry', 'Turkish manufacturers are increasingly adopting sustainable practices, from renewable energy usage to waste reduction programs. This commitment to environmental responsibility is becoming a key differentiator in global markets.', 'Zeynep Kaya', 'Sustainability Expert', 'Sustainability', ARRAY['sustainability', 'environment', 'green-manufacturing', 'responsibility'], '/placeholder.svg?height=400&width=600', true, 0, 0, 0, 'published'),
('Digital Transformation in Export Business', 'How technology is reshaping international trade', 'The digital revolution is transforming how Turkish companies conduct international business. From e-commerce platforms to digital documentation, technology is making exports more efficient and accessible.', 'Emre Şahin', 'Digital Strategy Manager', 'Technology', ARRAY['digital', 'technology', 'e-commerce', 'innovation'], '/placeholder.svg?height=400&width=600', false, 0, 0, 0, 'published');
